// Try Catch Finally=============================================

// try {
//     console.log("Trying to execute code...");
//     let x = y + 1; // ReferenceError
//   } catch (err) {
//     console.log("Error caught:", err.message);
//   } finally {
//     console.log("Finally block executed");
//   }
  


// throw error====================================================
// try {
//     console.log("Trying to execute code...");
//     let x =1+1
//     if(x==2){
//         throw new Error('it is an error')
//     }
    
//   } catch (err) {
//     console.log("Error caught:", err.message);
//   } finally {
//     console.log("Finally block executed");
//   }
  

// range Error======================================================

// try {
//     let arr = new Array(-5)
      
//     } catch (err) {
//         if(err instanceof RangeError){
//         console.log("range error:", err.message);
//         }else{
//             console.log('not range error')
//         }
//     } finally {
//       console.log("Finally block executed");
//     }



// strict mode ==================================================

// 'use strict'

// a = 12
// console.log(a)

